# reference the following tutorial series "Customize configs to run in production"
# https://pytorch-lightning.readthedocs.io/en/latest/levels/advanced_level_15.html

training:
  max_epochs: 5
  limit_train_batches: 0.10
  accelerator: "auto"
  devices: "auto"
  deterministic: True
  precision: 32
  strategy: single_device
  enable_checkpointing: True
  enable_progress_bar: True
  enable_model_summary: True
