github:
  prebuilds:
    master: false

tasks:
  - name: install dependencies
    init: |
      pip3 install - requirements.txt
      pip3 install -e .

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
