site_name: Lightning Pod

# docs_dir: sources

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate

repo_name: lightning-pod
repo_url: https://github.com/JustinGoheen/lightning-pod
edit_uri: ""

nav:
  - Overview: "index.md"
  - Additional: "additional.md"
  - Source Code: "sources/sourcecode.md"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
