name: Sphinx build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: bash docs/build_docs.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.0
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
